#!/usr/bin/env python3
"""Discord Bot Setup Wizard.

This script helps you set up your Discord bot step by step.
Run: python setup_discord.py
"""

import json
import os
import sys
from pathlib import Path


def print_header(text: str) -> None:
    """Print a formatted header."""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")


def print_step(num: int, text: str) -> None:
    """Print a step instruction."""
    print(f"\n📌 Step {num}: {text}")
    print("-" * 50)


def main():
    print_header("Discord Bot Setup Wizard")
    
    print("""
This wizard will help you set up your Discord bot.

You'll need:
1. A Discord account
2. A Discord server where you have admin permissions
3. Access to the Discord Developer Portal
    """)
    
    input("Press Enter to continue...")
    
    # Step 1: Create Discord Application
    print_step(1, "Create Discord Application")
    print("""
1. Go to: https://discord.com/developers/applications
2. Click 'New Application' (top right)
3. Name your application (e.g., 'AI Photo Bot')
4. Click 'Create'
5. On the General Information page, copy your 'Application ID'
    """)
    
    app_id = input("Paste your Application ID here: ").strip()
    
    # Step 2: Create Bot
    print_step(2, "Create Bot User")
    print("""
1. In your application, click 'Bot' in the left sidebar
2. Click 'Add Bot' then 'Yes, do it!'
3. Under 'Privileged Gateway Intents', enable:
   ✅ PRESENCE INTENT
   ✅ SERVER MEMBERS INTENT  
   ✅ MESSAGE CONTENT INTENT
4. Click 'Reset Token' to generate a new token
5. Copy the token (you won't be able to see it again!)
    """)
    
    bot_token = input("Paste your Bot Token here: ").strip()
    
    # Step 3: Invite Bot to Server
    print_step(3, "Invite Bot to Your Server")
    
    # Generate invite URL with proper permissions
    permissions = 8  # Administrator permission
    invite_url = (
        f"https://discord.com/api/oauth2/authorize"
        f"?client_id={app_id}"
        f"&permissions={permissions}"
        f"&scope=bot%20applications.commands"
    )
    
    print(f"""
1. Use this invite URL to add the bot to your server:

{invite_url}

2. Select your server from the dropdown
3. Click 'Continue' then 'Authorize'
4. Complete the CAPTCHA if prompted
    """)
    
    input("Press Enter after you've added the bot to your server...")
    
    # Step 4: Get Server ID
    print_step(4, "Get Your Server ID")
    print("""
1. In Discord, go to User Settings (gear icon)
2. Go to 'Advanced' and enable 'Developer Mode'
3. Right-click on your server name in the server list
4. Click 'Copy Server ID'
    """)
    
    guild_id = input("Paste your Server ID here: ").strip()
    
    # Step 5: Optional - Replicate API
    print_step(5, "Replicate API (for AI image generation)")
    print("""
This is optional but required for AI photo generation.

1. Go to: https://replicate.com/
2. Sign up or log in
3. Go to: https://replicate.com/account/api-tokens
4. Copy your API token
    """)
    
    replicate_token = input("Paste your Replicate API Token (or press Enter to skip): ").strip()
    
    # Step 6: Save Configuration
    print_step(6, "Saving Configuration")
    
    env_content = f"""# Discord Bot Configuration
# Generated by setup_discord.py

# Discord Settings
DISCORD_BOT_TOKEN={bot_token}
DISCORD_APPLICATION_ID={app_id}
DISCORD_GUILD_ID={guild_id}

# AI Image Generation (Replicate)
REPLICATE_API_TOKEN={replicate_token or 'your_replicate_token_here'}

# Bitcoin Payment Configuration (fill these in later)
BTC_RECEIVER_ADDRESS=your_btc_address_here
PAYMENT_WEBHOOK_SECRET=your_webhook_secret_here

# Pricing
PACK_USD_PRICE=25.0
PAYMENT_TIMEOUT_SECONDS=900

# Data Directory
DISCORD_AI_BOT_DATA_DIR=./data
"""
    
    env_path = Path(__file__).parent / ".env"
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print(f"✅ Configuration saved to: {env_path}")
    
    # Also create a config.json for the manager
    config_json = {
        "application_id": app_id,
        "guild_id": guild_id,
        "setup_complete": True,
    }
    
    config_path = Path(__file__).parent / "discord_config.json"
    with open(config_path, "w") as f:
        json.dump(config_json, f, indent=2)
    
    print(f"✅ Config JSON saved to: {config_path}")
    
    # Final instructions
    print_header("Setup Complete! 🎉")
    print(f"""
Your Discord bot is configured! Here's what you can do next:

1. Start the bot:
   cd {Path(__file__).parent}
   source venv/bin/activate
   python -m discord_ai_photo_bot.bot

2. Manage your server:
   python -m discord_ai_photo_bot.server_manager

3. Your invite URL (save this):
   {invite_url}

4. Important Files:
   - .env: Your bot credentials (keep this secret!)
   - discord_config.json: Server configuration

Need help? Check the README or Discord.py documentation.
    """)


if __name__ == "__main__":
    main()









